"""Prove a resumed run re-derived the same batches (P9-T03, P9-T04).

The assignment's bar is specific: after resume, no batch is skipped, no batch is
repeated, and `batch[N]` matches the pre-crash `batch[N]` in IDs, spans, and hashes.
All three are answered from the ledger itself, by comparing the crashed attempt's rows
against the resumed attempt's rows at the same `(global_step, microbatch_id)`.

That comparison is only meaningful because the crashed rows were never deleted. The
crashed attempt is the **expected** record and the resumed attempt is the **actual**
one, both generated by real runs, neither written by this module.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any, Sequence

from ledger.reader import load_consumption_ledger
from ledger.types import ConsumptionLedgerEvent

from .errors import RecoveryError

RESUME_VERIFICATION_FILENAME = "resume_verification.json"


@dataclass(frozen=True)
class BatchComparison:
    """One pre-crash batch against its post-resume re-derivation."""

    global_step: int
    microbatch_id: str
    expected_ledger_offset: int
    actual_ledger_offset: int
    expected_batch_content_hash: str
    actual_batch_content_hash: str
    expected_loss_mask_hash: str
    actual_loss_mask_hash: str
    sample_ids_match: bool
    token_spans_match: bool

    @property
    def matched(self) -> bool:
        return (
            self.expected_batch_content_hash == self.actual_batch_content_hash
            and self.expected_loss_mask_hash == self.actual_loss_mask_hash
            and self.sample_ids_match
            and self.token_spans_match
            and self.expected_ledger_offset == self.actual_ledger_offset
        )

    def to_dict(self) -> dict[str, Any]:
        return {
            "global_step": self.global_step,
            "microbatch_id": self.microbatch_id,
            "expected_ledger_offset": self.expected_ledger_offset,
            "actual_ledger_offset": self.actual_ledger_offset,
            "expected_batch_content_hash": self.expected_batch_content_hash,
            "actual_batch_content_hash": self.actual_batch_content_hash,
            "expected_loss_mask_hash": self.expected_loss_mask_hash,
            "actual_loss_mask_hash": self.actual_loss_mask_hash,
            "sample_ids_match": self.sample_ids_match,
            "token_spans_match": self.token_spans_match,
            "matched": self.matched,
        }


@dataclass(frozen=True)
class ResumeVerification:
    """Result of comparing a resumed attempt against the attempt that crashed."""

    run_id: str
    branch_id: str
    resumed_from_checkpoint_step: int
    resume_ledger_offset: int
    prior_attempt: int
    resumed_attempt: int
    comparisons: tuple[BatchComparison, ...]
    skipped_batches: tuple[str, ...]
    repeated_batches: tuple[str, ...]
    not_reached_batches: tuple[str, ...]
    offsets_contiguous: bool

    @property
    def mismatched(self) -> tuple[BatchComparison, ...]:
        return tuple(item for item in self.comparisons if not item.matched)

    @property
    def passed(self) -> bool:
        return (
            bool(self.comparisons)
            and not self.mismatched
            and not self.skipped_batches
            and not self.repeated_batches
            and self.offsets_contiguous
        )

    def to_dict(self) -> dict[str, Any]:
        return {
            "run_id": self.run_id,
            "branch_id": self.branch_id,
            "resumed_from_checkpoint_step": self.resumed_from_checkpoint_step,
            "resume_ledger_offset": self.resume_ledger_offset,
            "prior_attempt": self.prior_attempt,
            "resumed_attempt": self.resumed_attempt,
            "batches_compared": len(self.comparisons),
            "batches_matched": len(self.comparisons) - len(self.mismatched),
            "skipped_batches": list(self.skipped_batches),
            "repeated_batches": list(self.repeated_batches),
            "not_reached_batches": list(self.not_reached_batches),
            "offsets_contiguous": self.offsets_contiguous,
            "passed": self.passed,
            "comparisons": [item.to_dict() for item in self.comparisons],
        }


def verify_resume(
    ledger_path: Path,
    *,
    resume_ledger_offset: int,
    prior_attempt: int,
    resumed_attempt: int,
    resumed_from_checkpoint_step: int,
) -> ResumeVerification:
    """Compare the resumed attempt against the crashed one, batch by batch.

    `resume_ledger_offset` is the checkpoint's offset: the last batch the restored
    weights had already consumed. Everything the crashed attempt committed *after* it is
    what resume has to reproduce.
    """
    records = load_consumption_ledger(ledger_path)
    if not records:
        raise RecoveryError(f"cannot verify resume against an empty ledger: {ledger_path}")

    expected = [
        record
        for record in records
        if record.attempt == prior_attempt and record.ledger_offset > resume_ledger_offset
    ]
    actual = [record for record in records if record.attempt == resumed_attempt]
    if not actual:
        raise RecoveryError(f"no ledger rows found for attempt {resumed_attempt}")

    repeated = _duplicate_microbatch_ids(actual)
    actual_by_id = {record.microbatch_id: record for record in actual}
    highest_step_reached = max(record.global_step for record in actual)

    comparisons: list[BatchComparison] = []
    skipped: list[str] = []
    not_reached: list[str] = []

    for record in expected:
        replayed = actual_by_id.get(record.microbatch_id)
        if replayed is None:
            # A batch past the resumed run's stopping point was never due to be
            # re-consumed; only a gap *inside* the range it covered is a skip.
            if record.global_step > highest_step_reached:
                not_reached.append(record.microbatch_id)
            else:
                skipped.append(record.microbatch_id)
            continue
        comparisons.append(_compare(record, replayed))

    return ResumeVerification(
        run_id=actual[0].run_id,
        branch_id=actual[0].branch_id,
        resumed_from_checkpoint_step=resumed_from_checkpoint_step,
        resume_ledger_offset=resume_ledger_offset,
        prior_attempt=prior_attempt,
        resumed_attempt=resumed_attempt,
        comparisons=tuple(comparisons),
        skipped_batches=tuple(skipped),
        repeated_batches=repeated,
        not_reached_batches=tuple(not_reached),
        offsets_contiguous=_offsets_contiguous(actual, start=resume_ledger_offset + 1),
    )


def write_resume_verification(reports_dir: Path, verification: ResumeVerification) -> Path:
    """Write `reports/resume_verification.json` (P9-T04)."""
    from shards.io import write_json_atomic

    target = Path(reports_dir).resolve() / RESUME_VERIFICATION_FILENAME
    target.parent.mkdir(parents=True, exist_ok=True)
    write_json_atomic(target, verification.to_dict())
    return target


def _compare(
    expected: ConsumptionLedgerEvent,
    actual: ConsumptionLedgerEvent,
) -> BatchComparison:
    return BatchComparison(
        global_step=expected.global_step,
        microbatch_id=expected.microbatch_id,
        expected_ledger_offset=expected.ledger_offset,
        actual_ledger_offset=actual.ledger_offset,
        expected_batch_content_hash=expected.batch_content_hash,
        actual_batch_content_hash=actual.batch_content_hash,
        expected_loss_mask_hash=expected.loss_mask_hash,
        actual_loss_mask_hash=actual.loss_mask_hash,
        sample_ids_match=expected.packed_sample_ids == actual.packed_sample_ids,
        token_spans_match=expected.token_span_ids == actual.token_span_ids,
    )


def _duplicate_microbatch_ids(records: Sequence[ConsumptionLedgerEvent]) -> tuple[str, ...]:
    seen: set[str] = set()
    duplicates: list[str] = []
    for record in records:
        if record.microbatch_id in seen:
            duplicates.append(record.microbatch_id)
        seen.add(record.microbatch_id)
    return tuple(dict.fromkeys(duplicates))


def _offsets_contiguous(records: Sequence[ConsumptionLedgerEvent], *, start: int) -> bool:
    """The resumed attempt must pick up exactly at the checkpoint, with no holes."""
    offsets = [record.ledger_offset for record in records]
    return offsets == list(range(start, start + len(offsets)))
